name: flutter_application_1
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.1.0
  http: ^1.2.0
  path_provider: ^2.1.2
  spotify: ^0.13.0
  swipeable_page_route: ^0.4.2
  url_launcher: ^6.2.5
  google_fonts: ^4.0.1
  lottie: ^3.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter 

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/homepageanimation.json

